# Generated by Django 2.0.2 on 2018-02-14 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSubscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('subscribe_at', models.DateTimeField(auto_now_add=True)),
                ('unsubscribe_at', models.DateTimeField(blank=True, null=True)),
                ('is_subscriber', models.BooleanField(default=True)),
            ],
        ),
    ]
